nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': null
