controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_word_game: 
    path: '/api/word-game'
    controller: App\Controller\WordsController::play
    methods: [POST]
api_highscores:
    path: '/api/word-game'
    controller: App\Controller\WordsController::highscores
    methods: [GET]
